name: print hello world

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print hello world
        run: echo "Hello world"

      - name: Print name
        run: echo "BASANTA sHARMA"

      - name: print company name
        run: echo "Fintech Solution"